apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app-backend
  namespace: ecommerce-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ecommerce-app-backend
  template:
    metadata:
      labels:
        app: ecommerce-app-backend
    spec:
      containers:
      - image: khalidharbi/ecommerce-app-backend:latest
        name: ecommerce-app-backend
        ports:
        - containerPort: 3001
        envFrom:
        - configMapRef:
            name: dbconfig
        - secretRef:
            name: my-secret
        livenessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
